### ISSUE TITLE
Galaxy-brain radix exponentiation

### ISSUE THREAD

**Issue by oscbyspro** [oscbyspro/Numberick#22]
As it turns out, you can square the radix a bunch of times and then merge its partial squares. In the case where the radix is 3 (the worst case scenario), the number of multiplications required to create an AnyRadixUIntRoot instance is reduced from 40 to 11 on 64-bit machines. Similarly, this number goes from 19 to 9 when the radix is 10. So, that's nice.

**Comment by oscbyspro** [comment]
This method requires that the radix is not a power of two, but that's fine because those have trivial solutions anyway.

**Comment by oscbyspro** [comment]
Hm. It should also be possible to merge the exponents using bitwise AND rather than addition. Since it's a bunch of consecutive squares, the exponents must all unique powers of two, meaning that there's nothing to carry. That's quite neat, to be honest.

**Comment by oscbyspro** [comment]
You can also halve the cache's memory footprint by omitting the exponent, but that turned out to be slower.

**Comment by oscbyspro** [comment]
Hm. It's quite flat, plus-minus 2 elements, so wonder if skipping control-flow is better?

**Comment by mgriebling** [comment]
Cool research on speeding up string conversions.  And yes, sometimes benchmarks tell you a different story from what you might think.  Binary shifts are not necessarily faster than multiplication and, as you found, bitwise ORs may not be faster than addition.

**Comment by oscbyspro** [comment]
I've poured a lot of effort into it, but I've had the most success decoding.

### [UInt256 micro-benchmarks](https://github.com/oscbyspro/Numberick/blob/c30f4bd8044fc19eb352514579b54345d52db188/Tests/NBKDoubleWidthKitBenchmarks/256%2BText.swift)

| Test | NBK (main)  | ANK (v2.2.0) | Ratio |
|:----:|:-----------:|:------------:|:-----:|
| D10  | 16 ms       | 80 ms        | 5.0x  |
| D16  | 16 ms       | 78 ms        | 4.9x  |
| E10  | 53 ms       | 68 ms        | 1.3x  |
| E16  | 25 ms       | 26 ms        | 1.0x  |
