### ISSUE TITLE
Add a backported git branch

### ISSUE THREAD

**Issue by oscbyspro** [oscbyspro/Numberick#55]
This project will keep pace with Swift, but I'm open to the idea of backporting a git branch. Supporting Swift 5.7, iOS 14, drops StaticBigInt, but not much else. I have considered availability annotating things in the main branch, but you cannot conditionally add StaticBigInt in that way. Sad, I know. A 2nd git branch is probably the 2nd best option.

**Comment by ypopovych** [comment]
maybe also provide two versions. Like `0.9.xxx` for Swift 5.7 and '1.0.xxx` for Swift 5.8. So it can be added as a versioned dependency to Pods/SPM.

**Comment by oscbyspro** [comment]
Hm. I think I'll have to do something like that. I wish I could version branches independently...

**Comment by oscbyspro** [comment]
#### Some course correction

I'm noticing that I'm setting myself up for low-return-on-investment maintenance work with this dual-branch strategy, and that I'll need some course correction. So, here's the plan. It's 10x simpler, and achieves 95% of everything this aims to achieve. Drum-roll, please. I'll disable StaticBigInt by default, and anyone who want to use it (as I do) will have to toggle a value in the package manifest, or pass a build-time feature flag.

**Comment by ypopovych** [comment]
It's hard to pass parameters to the Package manifest when you have it as a dependency. But for now, I think the StaticBigInt feature is not a breaking one. The library can be used with a String constructor if you need a static big value somewhere. Maybe you can add a constructor from Words, it will also help for cases when you need static int somewhere and don't want to lose speed from String implementation
