### ISSUE TITLE
GitHub Actions usage limit?

### ISSUE THREAD

**Issue by oscbyspro** [oscbyspro/Numberick#60]
I had a look at [about-billing-for-github-actions](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions):

| Plan | Minutes (per month) |
|---|---|
| GitHub Free | 2,000 |

| Operating system | Minute multiplier |
|---|---|
| Linux | 1 |
| macOS | 10 |

The (#56) pull request says it took ~2h on macOS. 

1,200 GitHub-minutes per commit is unreasonable.

**Comment by oscbyspro** [comment]
And it's all just building the damn thing :sob:

```swift
Executed 291 tests, with 4 tests skipped and 0 failures (0 unexpected) in 1.246 (1.674) seconds
```

**Comment by ypopovych** [comment]
I have an idea.

Split tests to 4 different GA workflows:
1. Tests. Runs on each commit. macOS + Linux. Without `xcodebuild`. Without Benchmarks. Simple `swift test` command. No CocoaPods (they are slow). To test that nothing big is broken.
2. Full Tests. Runs on the new version tag event. All tests without benchmarks through `xcodebuild` and CocoaPods. The release should be done in 2 steps: tag, and then release from this tag (maybe draft release will work, should be checked in docs)
3. Deploy. Runs on a new release - deploy to CocoaPods.
4. Benchmarks - run on `workflow_dispatch` event manually if needed. Runs on all OSes / Xcode versions

**Comment by oscbyspro** [comment]
I like the idea of splitting it up, but you would need to `xcodebuild` to test a new commit, wouldn't you? Still, it might be viable if it's only on Linux. Dunno, would have to see how long it takes.

**Comment by ypopovych** [comment]
You can omit `xcodebuild` if you are building for macOS. You can simply run `swift test` command the same way as on Linux. To be exactly sure you can use `xcrun swift test` command and it will run `swift` binary from the active Xcode

**Comment by ypopovych** [comment]
BTW. You are not bound by 2000 minutes. This repository is an open-source (public) one. It has unlimited free minutes, though they will slow down runners from time to time if overused

**Comment by oscbyspro** [comment]
Good catch. I suppose I read it bit too fast:

> GitHub Actions usage is free for standard GitHub-hosted runners in public repositories, and for self-hosted runners.

**Comment by oscbyspro** [comment]
The (#63) Linux and macOS workflows run in about 2-3 minutes each, i.e. 22-33 GitHub-minutes.
