### ISSUE TITLE
StringLiteral until StaticBigInt

### ISSUE THREAD

**Issue by oscbyspro** [oscbyspro/Numberick#62]
Lowering the minimum platform requirements (#61) means that StaticBigInt be disabled by default. I'll add an ExpressibleByStringLiteral conformance to NBKDoubleWidth in its place. It will work like `init(_:radix:)` except it will also support the 3 most common radix prefixes: `0b`, `0o` and `0x`. So, ideally, the change is reduced to adding quotation marks.

**Comment by oscbyspro** [comment]
I suppose one somewhat surprising thing is that conforming to ExpressibleByStringLiteral causes `UInt256("123")` to call `init(stringLiteral:)` as opposed to `init?(_ description:)` from LosslessStringConvertible, because there's a special case for literals. So `UInt256(" 12")` crashes as instead of returning nil. Dunno, if that's a problem. It probably isn't given that literals are known at compile time.

**Comment by ypopovych** [comment]
one remark - enable String Literal for SBI too. Right now it will be disabled when the SBI flag is set. They can both be present.

**Comment by oscbyspro** [comment]
Your right in that these methods can coexist, but should they when one is clearly better? I suppose I can alleviate some migration pain by conditionally deprecating it. Or, do you have a use case in mind that prefers `init(stringLiteral:)` undeprecated? I'm thinking something like:


```swift
#if swift(>=5.8) && SBI
@available(swift, deprecated: 5.8, message: "Use an integer literal instead.")
#endif
@inlinable public init(stringLiteral source: StringLiteralType) { ... }
```

**Comment by ypopovych** [comment]
I think it can be used with some APIs which return strings with prefixes even if we have StaticBigInt. Maybe JSON-based API with big integers in it as hex values. I don't think it should be deprecated.

**Comment by ypopovych** [comment]
the method is good too. But I think we shouldn't force developers. If someone wants to use string literals - ok. Maybe they want to support older OSes without ifdefs even when they have StaticBigInt

**Comment by oscbyspro** [comment]
I changed `NBKDoubleWidth/StringLiteralType` to `StaticString` from `String`.

**Comment by oscbyspro** [comment]
I'll remove the deprecation because there isn't an automatic way of enabling StaticBigInt via availability.
